#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gts9wifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gts9wifi/proprietary/vendor/usr/idc/hall_wacom.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/hall_wacom.idc \
    vendor/samsung/gts9wifi/proprietary/vendor/usr/idc/sec_e-pen.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/sec_e-pen.idc \
    vendor/samsung/gts9wifi/proprietary/vendor/usr/idc/wacom_hall.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/wacom_hall.idc \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/audconf/OPEN/acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/acdb_cal.acdb \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/audconf/OPEN/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFileXml.qwsp \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/audio/sku_kalama/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_kalama/mixer_paths.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_r66451_amoled_cmd_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_r66451_amoled_cmd_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_r66451_amoled_video_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_r66451_amoled_video_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/backlight_calib_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/backlight_calib_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_GTS9P_ANA38407_AMSA24VU05.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_GTS9P_ANA38407_AMSA24VU05.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_GTS9U_ANA38407_AMSA46AS02.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_GTS9U_ANA38407_AMSA46AS02.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_GTS9_ANA38407_AMSA10FA01.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_GTS9_ANA38407_AMSA10FA01.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_2k_cmd_mode_qsync_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_2k_cmd_mode_qsync_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_2k_video_mode_qsync_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_2k_video_mode_qsync_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_qhd_cmd_mode_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_qhd_cmd_mode_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_nt36672e_lcd_video_mode_dsi_novatek_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt36672e_lcd_video_mode_dsi_novatek_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_nt36672e_lcd_video_mode_dsi_novatek_panel_without_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt36672e_lcd_video_mode_dsi_novatek_panel_without_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_r66451_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_r66451_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_r66451_amoled_cmd_mode_dsi_visionox_panel_without_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_r66451_amoled_cmd_mode_dsi_visionox_panel_without_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_r66451_amoled_video_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_r66451_amoled_video_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_r66451_amoled_video_mode_dsi_visionox_panel_without_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_r66451_amoled_video_mode_dsi_visionox_panel_without_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_sharp_1080p_cmd_mode_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_sharp_1080p_cmd_mode_dsi_panel.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/sensors/config/kailua_ak991x_5.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_5.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/sensors/config/kailua_bridge_driver_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_bridge_driver_0.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/sensors/config/kailua_veml3328_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_veml3328_0.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/sensors/config/kailua_veml3328_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_veml3328_1.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/sensors/config/veml3328_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/veml3328_0.json \
    vendor/samsung/gts9wifi/proprietary/vendor/etc/wifi/qca6490/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/qca6490/WCNSS_qcom_cfg.ini \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/GTS9_ANA38407_AMSA10FA01.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/GTS9_ANA38407_AMSA10FA01.dat \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/a740_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mbn \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/a740_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mdt \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/abov/a96t396_gts9_wifi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abov/a96t396_gts9_wifi.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/bt_nvm_loading.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/bt_nvm_loading_2nd.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading_2nd.xml \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot-calib.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l45-dsp1-spk-prot.wmfw \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/hpbtfw21.tlv \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.b9a:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.b9a \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.b9b:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.b9b \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.baa:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.baa \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.bb7:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.bb7 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.bb9:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.bb9 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.b9a:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.b9a \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.b9b:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.b9b \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.baa:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.baa \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.bb7:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.bb7 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.bb9:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.bb9 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/hpnv21g.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hpnv21g.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/keyboard_stm/stm32_gts9family.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/keyboard_stm/stm32_gts9family.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/amss20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/amss20.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlan.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlan.elf \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlan.elf1:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlan.elf1 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlan.elf10:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlan.elf10 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlan.elf2:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlan.elf2 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlang.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlang.elf \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlang.elf1:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlang.elf1 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlang.elf10:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlang.elf10 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/bdwlang.elf2:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/bdwlang.elf2 \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/m3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/m3.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/qca6490/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qca6490/regdb.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/tsp_stm/fts1ba90a_gts8p.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_stm/fts1ba90a_gts8p.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/tsp_stm/fts1ba90a_gts9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_stm/fts1ba90a_gts9.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/vpu30_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v.mbn \
    vendor/samsung/gts9wifi/proprietary/vendor/firmware/wez01_gts9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wez01_gts9.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_hynix_hi1337.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_hynix_hi1337.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.12_hynix_hi1337_front_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.12_hynix_hi1337_front_full.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_hynix_hi1337_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_hynix_hi1337_front.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.tuned.hynix_hi1337.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.hynix_hi1337.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.tuned.hynix_hi1337_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.hynix_hi1337_front.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/com.samsung.tuned.hynix_hi1337_front_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.hynix_hi1337_front_full.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/t_t10_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_t10_dual_calibration.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/gts9wifi/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin

PRODUCT_PACKAGES += \
    com.qti.eeprom.sec2qcconversion \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.samsung.node.capture_fusion \
    com.samsung.node.realtimebokeh \
    com.samsung.node.resolution \
    com.samsung.node.smooth_transition \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.samsung.node.uniplugin_vdis \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libTsAeFront_tabs9 \
    libTsAe_tabs9 \
    libdepthmapwrapper_secure \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8550 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qualcomm.mcx.distortionmapper \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libTsAf_TS9Q \
    libTsAwbFront_GTS9 \
    libTsAwb_GTS9 \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamximageformatutils \
    libcamxswispiqmodule \
    libchifeature2 \
    libcom.qti.chinodeutils \
    libsec2qc_conversion \
    libthirdparty_zoomtranslator_imp \
    libtriplecam_image_optical_zoom \
    sensors.grip \
    sensors.ssc \
    factory.ssc
